const fs = require('fs');

let jsonData = {
  // //资源事实表
  // resource_fact: {
  //   'hq_resourcetype_sk' : '资源类型代理键',
  //   'hq_resourcestatus_sk' : '资源状态代理键',
  //   'hq_level_sk' : '公司层级代理键',
  //   'hq_id_sk' : '时间维度代理键',
  //   'hq_oldcode' : '资源旧编码',
  //   'hq_resourcearea' : '资源面积',
  //   'hq_usablearea' : '建筑面积',
  //   'hq_excuteprice' : '执行租金',
  //   'hq_managementprice' : '标准管理费',
  //   'hq_datetime' : '日期',
  //   'hq_rented' : '已出租标志',
  //   'hq_notrented' : '未出租标志',
  //   'hq_gradeprice' : '等级定价',
  //   'hq_standardprice' : '标准租金',
  //   'hq_paymentmoney' : '合同总金额',
  //   'hq_unitpaymoney' : '签约单价',
  //   'hq_rentend_resourcearea' : '已出租资源面积',
  //   'hq_notrentend_resourcearea' : '未出租资源面积',
  //   'hq_rentend_usablearea' : '已出租建筑面积',
  //   'hq_notrentend_usablearea' : '未出租建筑面积',
  //   'hq_rentend_excuteprice' : '已出租执行租金',
  //   'hq_notrentend_excuteprice' : '未出租执行租金',
  //   'hq_rentend_managementprice' : '已出租标准管理费',
  //   'hq_notrentend_managementprice' : '未出租标准管理费',
  //   'hq_rentend_gradeprice' : '已出租等级定价',
  //   'hq_notrentend_gradeprice' : '未出租等级定价',
  //   'hq_rentend_standardprice' : '已出租标准租金',
  //   'hq_notrentend_standardprice' : '未出租标准租金',
  //   'hq_rentend_paymentmoney' : '已出租合同总金额',
  //   'hq_notrentend_paymentmoney' : '未出租合同总金额',
  //   'hq_rentend_unitpaymoney' : '已出租签约单价',
  //   'hq_notrentend_unitpaymoney' : '未出租签约单价',
  //   'hq_rentend1' : '已出租预留字段1',
  //   'hq_notrentend1' : '未出租预留字段1',
  //   'hq_rentend2' : '已出租预留字段2',
  //   'hq_notrentend2' : '未出租预留字段2',
  //   'hq_rentend3' : '已出租预留字段3',
  //   'hq_notrentend3' : '未出租预留字段3',
  //   'hq_rentend4' : '已出租预留字段4',
  //   'hq_notrentend4' : '未出租预留字段4',
  //   'hq_rentend5' : '已出租预留字段5',
  //   'hq_notrentend5' : '未出租预留字段5',
  //   'hq_rentend6' : '已出租预留字段6',
  //   'hq_notrentend6' : '未出租预留字段6',
  //   'hq_rentend7' : '已出租预留字段7',
  //   'hq_notrentend7' : '未出租预留字段7',
  //   'hq_rentend8' : '已出租预留字段8',
  //   'hq_notrentend8' : '未出租预留字段8',
  //   'hq_rentend9' : '已出租预留字段9',
  //   'hq_notrentend9' : '未出租预留字段9',
  //   'hq_rentend10' : '已出租预留字段10',
  //   'hq_notrentend10' : '未出租预留字段10'
  // },
  // //资源类型维度表
  // resourcetype_dim: {
  //   'hq_resourcetype_sk': '资源类型代理键',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  //   'hq_resourcetypecode': '资源类型编码',
  //   'hq_resourcetypename': '资源类型',
  //   'hq_custypename': '铺位类别',
  // },
  // //资源状态维度表
  // resourcestatus_dim: {
  //   'hq_resourcestatus_sk': '资源状态代理键',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  //   'hq_resourcestatuscode': '资源状态编码',
  //   'hq_resourcestatusname': '资源状态',
  // },
  // //公司层级维度表
  // leveldimension_dim: {
  //   'hq_level_sk': '公司层级代理键',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  //   'hq_matchcode': '公司层级编码',
  //   'hq_companyname': '公司名称',
  //   'hq_building': '楼栋',
  //   'hq_floor': '楼层',
  //   'hq_subarea': '分区',
  //   'hq_operatingdivision': '经营分区',
  //   'hq_pk_corp': '公司编码',
  //   'hq_grade': '资源等级',
  // },
  // //合同事实表
  // CONTRACT_FACT: {
    // 'hq_contractstatus_sk': '合同状态代理键',
    // 'hq_kind_sk': '业种代理键',
    // 'hq_id_sk': '时间代理键',
    // 'hq_contracttype_sk': '合同类型代理键',
    // 'hq_category_sk': '合同类别代理键',
    // 'hq_level_sk': '公司层级代理键',
    // 'hq_merchant_sk': '商户代理键',
    // 'hq_paymentproject_sk': '缴费项目代理键',
    // 'hq_smuser_sk': '系统人员代理键',
    // 'hq_resourcetype_sk': '资源类型代理键',
    // 'hq_contractcode': '合同编码',
    // 'hq_contractno': '合同号',
    // 'hq_oldcode': '资源旧编码',
    // 'hq_contractstartdate': '合同开始日期',
    // 'hq_contractenddate': '合同结束日期',
  //   'hq_contractmoney': '合同总金额',
  //   'hq_resourcearea': '资源面积',
  //   'hq_usablearea': '建筑面积',
  //   'hq_gradeprice': '等级定价',
  //   'hq_standardprice': '标准租金',
  //   'hq_excuteprice': '执行租金',
  //   'hq_managementprice': '标准管理费',
  //   'hq_paymentmoney': '合同租金单价',
  //   'hq_discount': '折扣',
  //   'hq_unitpaymoney': '签约单价',
  //   'hq_datetime': '入库日期',
  //   'hq_filterdate': '日期',
  //   'shouldchanged': '应续约标志',
  //   'changed': '已续约标志',
  //   'shouldrenewed': '应续租标志',
  //   'renewed': '已续租标志',
  //   'notrefunded': '未退租标志',
  //   'refunded': '已退租标志',
  //   'hq_shouldchanged_contractmoney': '应续约合同总金额',
  //   'hq_changed_contractmoney': '已续约合同总金额',
  //   'hq_shouldrenewed_contractmoney': '应续租合同总金额',
  //   'hq_renewed_contractmoney': '已续租合同总金额',
  //   'hq_notrefunded_contractmoney': '未退租合同总金额',
  //   'hq_refunded_contractmoney': '已退租合同总金额',
  //   'hq_shouldchanged_resourcearea': '应续约资源面积',
  //   'hq_changed_resourcearea': '已续约资源面积',
  //   'hq_shouldrenewed_resourcearea': '应续租资源面积',
  //   'hq_renewed_resourcearea': '已续租资源面积',
  //   'hq_notrefunded_resourcearea': '未退租资源面积',
  //   'hq_refunded_resourcearea': '已退租资源面积',
  //   'hq_shouldchanged_usablearea': '应续约建筑面积',
  //   'hq_changed_usablearea': '已续约建筑面积',
  //   'hq_shouldrenewed_usablearea': '应续租建筑面积',
  //   'hq_renewed_usablearea': '已续租建筑面积',
  //   'hq_notrefunded_usablearea': '未退租建筑面积',
  //   'hq_refunded_usablearea': '已退租建筑面积',
  //   'hq_shouldchanged_gradeprice': '应续约等级定价',
  //   'hq_changed_gradeprice': '已续约等级定价',
  //   'hq_shouldrenewed_gradeprice': '应续租等级定价',
  //   'hq_renewed_gradeprice': '已续租等级定价',
  //   'hq_notrefunded_gradeprice': '未退租等级定价',
  //   'hq_refunded_gradeprice': '已退租等级定价',
  //   'hq_shouldchanged_standardprice': '应续约标准租金',
  //   'hq_changed_standardprice': '已续约标准租金',
  //   'hq_shouldrenewed_standardprice': '应续租标准租金',
  //   'hq_renewed_standardprice': '已续租标准租金',
  //   'hq_notrefunded_standardprice': '未退租标准租金',
  //   'hq_refunded_standardprice': '已退租标准租金',
  //   'hq_shouldchanged_excuteprice': '应续约执行租金',
  //   'hq_changed_excuteprice': '已续约执行租金',
  //   'hq_shouldrenewed_excuteprice': '应续租执行租金',
  //   'hq_renewed_excuteprice': '已续租执行租金',
  //   'hq_notrefunded_excuteprice': '未退租执行租金',
  //   'hq_refunded_excuteprice': '已退租执行租金',
  //   'hq_shouldchanged_managementprice': '应续约标准管理费',
  //   'hq_changed_managementprice': '已续约标准管理费',
  //   'hq_shouldrenewed_managementprice': '应续租标准管理费',
  //   'hq_renewed_managementprice': '已续租标准管理费',
  //   'hq_notrefunded_managementprice': '未退租标准管理费',
  //   'hq_refunded_managementprice': '已退租标准管理费',
  //   'hq_shouldchanged_paymentmoney': '应续约合同租金单价',
  //   'hq_changed_paymentmoney': '已续约合同租金单价',
  //   'hq_shouldrenewed_paymentmoney': '应续租合同租金单价',
  //   'hq_renewed_paymentmoney': '已续租合同租金单价',
  //   'hq_notrefunded_paymentmoney': '未退租合同租金单价',
  //   'hq_refunded_paymentmoney': '已退租合同租金单价',
  //   'hq_shouldchanged_discount': '应续约折扣',
  //   'hq_changed_discount': '已续约折扣',
  //   'hq_shouldrenewed_discount': '应续租折扣',
  //   'hq_renewed_discount': '已续租折扣',
  //   'hq_notrefunded_discount': '未退租折扣',
  //   'hq_refunded_discount': '已退租折扣',
  //   'hq_shouldchanged_unitpaymoney': '应续约签约单价',
  //   'hq_changed_unitpaymoney': '已续约签约单价',
  //   'hq_shouldrenewed_unitpaymoney': '应续租签约单价',
  //   'hq_renewed_unitpaymoney': '已续租签约单价',
  //   'hq_notrefunded_unitpaymoney': '未退租签约单价',
  //   'hq_refunded_unitpaymoney': '已退租签约单价',
  // },
  // //合同类别维度表
  // CONTRACT_CATEGORY_DIM: {
  //   'hq_category_sk': '合同类别代理键',
  //   'hq_categorycode': '合同类别编码',
  //   'hq_categoryname': '合同类别',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  // },
  // //合同状态维度表
  // CONTRACT_CONTRACTSTATUS_DIM: {
  //   'hq_contractstatus_sk': '合同状态代理键',
  //   'hq_contractstatuscode': '合同状态编码',
  //   'hq_contractstatusname': '合同状态',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  // },
  // //业种维度表
  // CONTRACT_KIND_DIM: {
  //   'hq_kind_sk': '业种代理键',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  //   'hq_kindcode': '业种编码',
  //   'hq_pk_corp': '公司编码',
  //   'hq_bkindname': '业种大类',
  //   'hq_lkindname': '业种小类',
  // },
  // //商户维度表
  // CONTRACT_MERCHANT_DIM: {
  //   'hq_merchant_sk': '商户代理键',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  //   'hq_merchantcode': '商户编码',
  //   'hq_merchantname': '商户名称',
  //   'hq_certificatetype': '证件类型',
  //   'hq_certificateno': '证件号码',
  //   'hq_merchanttype': '商户类型',
  //   'hq_mobilephone': '联系方式',
  // },
  // //缴费项目维度表
  // CONTRACT_PAYMENTPROJECT_DIM: {
  //   'hq_paymentproject_sk': '缴费项目代理键',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  //   'hq_paymentprojectcode': '缴费项目编码',
  //   'hq_paymentprojectname': '缴费项目',
  // },
  // //合同类型维度表
  // CONTRACT_CONTRACTTYPE_DIM: {
  //   'hq_contracttype_sk': '合同类型代理键',
  //   'hq_contracttypecode': '合同类型编码',
  //   'hq_contracttypename': '合同类型',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  // },
  // //系统用户维度表
  // SMUSER_DIM: {
  //   'hq_smuser_sk': '系统用户代理键',
  //   'hq_version': '版本号',
  //   'hq_effective_date': '有效日期开始时间',
  //   'hq_expiry_date': '有效日期结束时间',
  //   'hq_cuserid': '人员ID',
  //   'hq_username': '姓名',
  //   'hq_email': '邮箱',
  //   'hq_phone': '手机号',
  //   'hq_workno': '工号'
  // },
  // //时间维度表
  // f_date_dim: {
  //   'hq_date_sk' : '数据日期代理键',
  //   'hq_f_key' : '日期（时间戳格式）',
  //   'hq_f_date' : '日期（YYYY-MM-DD）',
  //   'hq_f_year' : '年',
  //   'hq_f_quarter' : '季度',
  //   'hq_f_month' : '月',
  //   'hq_f_week' : '周',
  //   'hq_f_weekofday' : '周几',
  //   'hq_f_day' : '日',
  //   'hq_f_dayofyear' : '一年中的第几天',
  //   'hq_f_beginofmonth' : '月初',
  //   'hq_f_endofmonth' : '月末'
  // },
  // //填报招商业绩明细
  // tb_zsyj_mx_fact: {
  //   'hq_date_sk' : '时间代理键',
  //   'operator_sk' : '员工代理键',
  //   'HQ_OLDCODE' : '铺位号',
  //   'HQ_BUNK_TYPE' : '铺位类型',
  //   'HQ_BUNK_GRADE' : '铺位等级',
  //   'HQ_CONTRACT_TIME' : '签约时间',
  //   'HQ_CONTRACT_PARTY' : '签约方',
  //   'HQ_AREA' : '签约面积',
  //   'HQ_RENT' : '签约租金',
  //   'HQ_IS_OBN' : '是否老带新',
  //   'HQ_TASK_NUMBERS' : '基本任务数',
  //   'HQ_ACCOMPLISH_NUMBERS' : '完成签约数',
  //   'HQ_BONUS' : '奖励金额',
  //   'HQ_MARK' : '备注',
  //   'inhivetime' : '入库时间'
  // },
  // //填报招商业绩分析
  // tb_zsyj_fx_fact: {
    // 'hq_date_sk' : '时间代理键',
    // 'operator_sk' : '员工代理键',
    // 'HQ_CONTRACT_TIME' : '签约时间',
    // 'HQ_BUNK_TYPE' : '铺位类型',
    // 'HQ_AREA' : '签约面积',
    // 'HQ_RENT' : '签约租金',
    // 'HQ_BONUS' : '奖励金额',
    // 'HQ_TASK_NUMBERS' : '基本任务数',
    // 'HQ_ACCOMPLISH_NUMBERS' : '完成签约数',
    // 'inhivetime' : '入库时间'
  // },
  // //填报招商业绩公司人员维度表
  // tb_zsyj_operator_dim: {
  //   'operator_sk' : '员工代理键',
  //   'version' : '版本号',
  //   'effective_date' : '生效日期',
  //   'expiry_date' : '过期时间',
  //   'HQ_COMPANY_NAME' : '公司名',
  //   'HQ_DEPARTMENT' : '部门',
  //   'HQ_OPERATOR' : '招商经办人'
  // },
  // //收款事实表
  // receiptdoc_fact_dim: {
    // 'hq_receiptdocnumber': '收款单据号',
    // 'hq_chargetype_sk': '应收实收代理键',
    // 'hq_chargestatus_sk': '缴费状态代理键',
    // 'hq_paymentproject_sk': '缴费项目代理键',
    // 'hq_id_sk': '日期代理键',
    // 'hq_smuser_sk': '系统用户代理键',
    // 'hq_merchant_sk': '商户代理键',
    // 'hq_contract_sk': '合同代理键',
    // 'hq_resource_sk': '资源代理键',
    // 'hq_recievablemark0': '应收标志',
    // 'hq_reallymark1': '实收标志',
    // 'hq_reallydate': '日期',
    // 'hq_inhivetime': '入库时间'
  // },
  // //缴费状态维度表
  // CONTRACT_CHARGESTATUS_DIM: {
  //   'hq_chargestatus_sk': '缴费状态代理键',
  //   'hq_chargestatuscode': '缴费状态编码',
  //   'hq_chargestatusname': '缴费状态名称',
  //   'version' : '版本号',
  //   'effective_date' : '生效日期',
  //   'expiry_date' : '过期时间',
  // },
  // //资源维度表
  // RESOURCE_DIMENSION_DIM: {
  //   'hq_resource_sk': '资源维度代理键',
  //   'version' : '版本号',
  //   'effective_date' : '生效日期',
  //   'expiry_date' : '过期时间',
  //   'hq_resourcecode': '资源维度编码',
  //   'hq_oldcode': '资源旧编码',
  //   'hq_resourcetype': '资源类型',
  //   'hq_resourcestatus': '资源状态',
  //   'hq_buliding': '楼栋',
  //   'hq_floor': '楼层',
  //   'hq_subarea': '分区',
  //   'hq_pk_areamanage': '经营分区',
  //   'hq_maker': '备注',
  //   'hq_pk_corp': '公司编码',
  //   'hq_grade': '等级',
  //   'hq_companyname': '公司名'
  // },
  // //应收实收维度表
  // CHARGETYPE_DIMENSION_DIM: {
  //   'hq_chargetype_sk': '应收实收代理键',
  //   'hq_chargetypename': '应收/实收',
  //   'version' : '版本号',
  //   'effective_date' : '生效日期',
  //   'expiry_date' : '过期时间',
  // },
  // //合同维度表
  // CONTRACT_DIMENSION_DIM: {
  //   'hq_contract_sk': '合同维度代理键',
  //   'version' : '版本号',
  //   'effective_date' : '生效日期',
  //   'expiry_date' : '过期时间',
  //   'hq_contractcode': '合同编码',
  //   'hq_contracttype': '合同类型',
  //   'hq_category': '合同类别',
  //   'hq_constartime': '合同开始时间',
  //   'hq_constoptime': '合同结束时间',
  //   'hq_contractmoney': '合同总金额',
  //   'hq_bkindname': '业种大类',
  //   'hq_lkindname': '业种小类',
  //   'hq_contractmaker': '合同备注',
  //   'hq_resourcecode': '资源编码',
  //   'hq_oldcode': '资源旧编码',
  //   'hq_pk_corp': '公司编码',
  //   'hq_companyname1': '公司名称',
  //   'hq_vbillstatus': '审批状态'
  // },
  //利润分析
  // TB_HQMART_PLANBUDGET_FACT: {
  //   'hq_level_sk': '公司层级代理键',
  //   'hq_pid': '项目ID',
  //   'hq_projectname': '项目名称',
  //   'hq_pk_corp': '公司编码',
  //   'hq_year': '年',
  //   'hq_month': '月',
  //   'hq_budget': '预算费用标记',
  //   'hq_actual': '实际费用标记',
  //   'hq_budgetmoney': '预算金额',
  //   'hq_actualmoney': '实际金额',
  //   'hq_category': '标记',
  //   'hq_categoryid': '收入标记',
  //   'hq_createtime': '创建日期',
  // },
// hana 销售业绩汇总表
 hana1: {
   'LIPS_MANDT': '',
   'LIPS_VBELN': '',
   'LIKP_WADAT_IST': '年度',
   'LIKP_VKORG': '公司代码',
   'LIKP_KUNAG': '客户编码',
   'T001_BUTXT': '公司代码描述',
   'BUT000_NAME_ORG1': '客户编码描述',
   'VBAK_ZXSBGS': '销售办公室',
   'VBAK_ZXSZ': '销售组',
   'VBAK_ZXSXZ': '销售小组',
   'ZSDT001_ZXSBGS_TXT': '销售办公室描述',
   'ZSDT002_ZXSZ_TXT': '销售组描述',
   'ZSDT003_ZXSXZ_TXT': '销售小组描述',
   'VBPA_LIFNR': '业务员',
   'BUT000_NAME_LAST': '业务员描述',
   'MARA_MATKL': '物料组',
   'MAKT_MAKTX': '物料描述',
   'MARC_ZZCPX': '产品线',
   'ZMMT002_ZZCPX_TXT': '产品线描述',
   'CURRENCY': '币种',
   'SHIPPING_AMOUNT': '出货总金额',
   'VBAP_KWMENG': '出货总金额KWMNG',
  }
};

function e2cn() {
  Object.keys(jsonData).forEach((i) => {
    let obj = jsonData[i];
    Object.keys(obj).forEach((j) => {
      let resultStr = `update t_fields set fdesc = '${obj[j]}' where fname = '${j}';`;
      fs.writeFile('./message.txt', resultStr + '\n',{ 'flag': 'a' },function(err){
        if(err) console.log('写文件操作失败');
        // else console.log('写文件操作成功');
      });
    })
  })
}

e2cn();